project_id = "khwjrkficzshbcfnppfn"

[functions.mega-chat]
verify_jwt = false

[functions.mega-research]
verify_jwt = false

[functions.mega-code]
verify_jwt = false

[functions.mega-image]
verify_jwt = false

[functions.mega-document]
verify_jwt = false

[functions.mega-math]
verify_jwt = false
